import type { defaultRegistry } from './index.ts'

type Routes = (typeof defaultRegistry)['routes']

/**
 * Pre-computed API definition tree for tests
 * This mirrors what would be generated by the backend generator
 */
export interface ApiDefinition {
  auth: {
    login: Routes['auth.login'] & {
      show: Routes['auth.login.show']
    }
    register: Routes['auth.register']
  }
  users: {
    index: Routes['users.index']
    bar: Routes['users.bar']
    store: Routes['users.store']
    show: Routes['users.show']
  }
  posts: {
    comments: {
      likes: {
        detail: Routes['posts.comments.likes.detail']
        toggle: Routes['posts.comments.likes.toggle']
      }
    }
  }
  products: {
    search: Routes['products.search']
    store: Routes['products.store']
  }
  subscriberLists: {
    store: Routes['subscriber_lists.store']
    index: Routes['subscriber_lists.index']
    show: Routes['subscriber-lists.show']
  }
}
