/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  Contacts: () => import('#controllers/contacts_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Products: () => import('#controllers/products_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
