import type { SchemaEndpoint } from '@tuyau/core/types'
import type { DataTag } from '@tanstack/query-core'
import type { DefinedInitialDataOptions, UndefinedInitialDataOptions } from '@tanstack/svelte-query'
import type { CreateInfiniteQueryOptions } from '@tanstack/svelte-query'
import type { InitialDataFunction, NonUndefinedGuard } from '@tanstack/query-core'
import type {
  TuyauQueryKey,
  TuyauMutationKey,
  TuyauRequestOptions,
  TuyauQueryBaseOptions,
  DecorateRouterKeyable,
  DistributiveOmit,
  WithRequired,
} from '@tuyau/query-core'

import type { DecorateQueryFn } from './query.ts'
import type { DecorateMutationFn } from '../mutation.ts'
import type { DecorateInfiniteQueryFn } from './infinite_query.ts'

export type {
  TuyauQueryKey,
  TuyauMutationKey,
  TuyauQueryBaseOptions,
  DecorateRouterKeyable,
  DistributiveOmit,
  WithRequired,
  TuyauRequestOptions,
}
export type { QueryType } from '@tuyau/query-core'

type ReservedQueryOptions = 'queryKey' | 'queryFn' | 'queryHashFn' | 'queryHash'

/**
 * Query options input when `initialData` is defined.
 * Omits reserved keys that are auto-generated by Tuyau
 */
export type DefinedTuyauQueryOptionsIn<TQueryFnData, TData, TError> = DistributiveOmit<
  DefinedInitialDataOptions<TQueryFnData, TError, TData, TuyauQueryKey>,
  ReservedQueryOptions
> &
  TuyauQueryBaseOptions

/**
 * Query options input when `initialData` is undefined (default case).
 * Omits reserved keys that are auto-generated by Tuyau
 */
export type UndefinedTuyauQueryOptionsIn<TQueryFnData, TData, TError> = DistributiveOmit<
  UndefinedInitialDataOptions<TQueryFnData, TError, TData, TuyauQueryKey>,
  ReservedQueryOptions
> &
  TuyauQueryBaseOptions

/**
 * Fully resolved query options with defined initial data,
 * ready to be passed to Svelte's `createQuery`.
 * The `queryKey` is branded with `DataTag` for type-safe cache access
 */
export type DefinedTuyauQueryOptionsOut<TQueryFnData, TData, TError> = DefinedInitialDataOptions<
  TQueryFnData,
  TError,
  TData,
  TuyauQueryKey
> & {
  queryKey: DataTag<TuyauQueryKey, TData, TError>
}

/**
 * Fully resolved query options with undefined initial data,
 * ready to be passed to Svelte's `createQuery`.
 * The `queryKey` is branded with `DataTag` for type-safe cache access
 */
export type UndefinedTuyauQueryOptionsOut<TQueryFnData, TData, TError> =
  UndefinedInitialDataOptions<TQueryFnData, TError, TData, TuyauQueryKey> & {
    queryKey: DataTag<TuyauQueryKey, TData, TError>
  }

type ReservedInfiniteQueryOptions = 'queryKey' | 'queryFn' | 'queryHashFn' | 'queryHash'

/**
 * Tuyau-specific infinite query option allowing the user to specify
 * which request parameter holds the page value
 */
interface TuyauInfiniteQueryBaseOptionsIn {
  /**
   * The key used for the page parameter in the request query.
   * For example, if your API expects `?page=1`, set this to `'page'`.
   * If your API expects `?cursor=abc`, set this to `'cursor'`.
   * Defaults to `'page'`
   */
  pageParamKey?: string
}

/**
 * Infinite query options input when `initialData` is undefined (default case).
 * Svelte Query does not export dedicated Defined/Undefined infinite variants,
 * so we construct them from `CreateInfiniteQueryOptions` directly
 */
export type UndefinedTuyauInfiniteQueryOptionsIn<TQueryFnData, TError, TData> = DistributiveOmit<
  CreateInfiniteQueryOptions<TQueryFnData, TError, TData, TuyauQueryKey, unknown>,
  ReservedInfiniteQueryOptions
> &
  TuyauQueryBaseOptions &
  TuyauInfiniteQueryBaseOptionsIn & {
    initialData?: undefined
  }

/**
 * Fully resolved infinite query options with undefined initial data,
 * ready to be passed to Svelte's `createInfiniteQuery`
 */
export type UndefinedTuyauInfiniteQueryOptionsOut<TQueryFnData, TError, TData> =
  CreateInfiniteQueryOptions<TQueryFnData, TError, TData, TuyauQueryKey, unknown> & {
    queryKey: DataTag<TuyauQueryKey, TData>
  }

/**
 * Infinite query options input when `initialData` is defined
 */
export type DefinedTuyauInfiniteQueryOptionsIn<TQueryFnData, TError, TData> = DistributiveOmit<
  CreateInfiniteQueryOptions<TQueryFnData, TError, TData, TuyauQueryKey, unknown>,
  ReservedInfiniteQueryOptions
> &
  TuyauQueryBaseOptions &
  TuyauInfiniteQueryBaseOptionsIn & {
    initialData:
      | NonUndefinedGuard<TQueryFnData>
      | InitialDataFunction<NonUndefinedGuard<TQueryFnData>>
  }

/**
 * Fully resolved infinite query options with defined initial data,
 * ready to be passed to Svelte's `createInfiniteQuery`
 */
export type DefinedTuyauInfiniteQueryOptionsOut<TQueryFnData, TError, TData> =
  CreateInfiniteQueryOptions<TQueryFnData, TError, TData, TuyauQueryKey, unknown> & {
    queryKey: DataTag<TuyauQueryKey, TData>
  }

/**
 * Union of all infinite query options input types.
 * Used internally when the exact initialData variant is not known
 */
export type AnyTuyauInfiniteQueryOptionsIn<TQueryFnData, TError, TData> =
  | UndefinedTuyauInfiniteQueryOptionsIn<TQueryFnData, TError, TData>
  | DefinedTuyauInfiniteQueryOptionsIn<TQueryFnData, TError, TData>

type EndpointKeys = 'methods' | 'pattern' | 'types'

/**
 * Determines if an endpoint uses query methods (GET/HEAD) or mutation methods
 */
type IsQueryMethod<E extends SchemaEndpoint> = E['methods'][number] extends infer M
  ? M extends 'GET' | 'HEAD'
    ? true
    : false
  : false

/**
 * Resolves the available TanStack Query decorators for an endpoint.
 * GET/HEAD endpoints get query + infinite query methods.
 * Other methods (POST, PUT, etc.) get mutation methods.
 * All endpoints get path-level key/filter methods
 */
export type EndpointNode<E extends SchemaEndpoint> = (IsQueryMethod<E> extends true
  ? DecorateQueryFn<E> & DecorateInfiniteQueryFn<E>
  : DecorateMutationFn<E>) &
  DecorateRouterKeyable

/**
 * Recursively transforms a route tree into a Svelte Query client type.
 * Each endpoint node gets query/mutation decorators, and nested
 * route segments are recursively transformed. Every level also
 * gets path-level key/filter methods via `DecorateRouterKeyable`
 */
export type TransformToSvelteQuery<T> = {
  [K in keyof T]: T[K] extends SchemaEndpoint
    ? EndpointNode<T[K]> & TransformToSvelteQuery<Omit<T[K], EndpointKeys>>
    : TransformToSvelteQuery<T[K]>
} & DecorateRouterKeyable

/**
 * Top-level type for a Tuyau Svelte Query client
 */
export type TuyauSvelteQuery<R extends Record<string, SchemaEndpoint>> = TransformToSvelteQuery<R>
